### ROOT SERVER
GET http://localhost:4000/
### CHESS ROOT ENDPOINT
GET http://localhost:4000/chess

### Users
GET http://localhost:4000/user/

### Users
POST  http://localhost:4000/user/register

{
    "email": "email",
    "username" : "new_user",
    "password": "password"
}